#! /bin/bash

if [ $# -lt 1 ]; then
    exit 0
fi

pattern=$(expr "$*" : '.*@\(.*\):.*')

while read line
do
    host=($line)
    if [ ${host[0]} = $pattern ]; then
        ip=${host[1]}
    fi
done < /etc/password/host

info="$*"

if [ -n "$ip" ]; then
    info=${*/$pattern/$ip}
fi

echo $info

sshpass -p 'password' scp $info
