#! /bin/bash

if [ $# -lt 1 ]; then
    exit 0
fi

pattern=$(expr "$*" : '.*@\(.*\):.*')
info="$*"

if [ -n "$pattern" ]; then
    while read line
    do
        host=($line)
        if [ ${host[0]} = $pattern ]; then
            ip=${host[1]}
        fi
    done < /etc/password/host
    
    
    if [ -n "$ip" ]; then
        info=${*/$pattern/$ip}
    fi
fi

echo $info

sshpass -p 'password' scp $info
