#! /bin/bash

if [ $# -lt 1 ]; then
    exit 0
fi

while read line
do
    host=($line)
    if [ ${host[0]} = $1 ]; then
        ip=${host[1]}
    fi
done < /etc/password/host

echo $ip

sshpass -p 'password' ssh username@$ip

